version: '3'

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - fullnet
    depends_on:
      - app

  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    networks:
      - fullnet
    volumes:
      - ./node:/home/node/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fullcycle
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - fullnet

networks:
  fullnet:
    driver: bridge
      